import { StyleSheet } from 'react-native';

export const callsPalette = {
  light: {
    bg: '#F0F2F5',
    card: '#FFFFFF',
    cardBorder: 'rgba(0,0,0,0.06)',
    unreadBg: '#EEF2FF',
    primary: '#6366F1',
    primaryMuted: 'rgba(99,102,241,0.12)',
    success: '#10B981',
    danger: '#EF4444',
    warning: '#F59E0B',
    text: '#1E293B',
    textSecondary: '#475569',
    textMuted: '#64748B',
    textFaint: '#94A3B8',
    divider: 'rgba(0,0,0,0.06)',
    inputBg: 'rgba(0,0,0,0.04)',
    bubbleIn: '#F1F5F9',
    bubbleInText: '#1E293B',
    bubbleOut: '#6366F1',
    bubbleOutText: '#FFFFFF',
    noteBg: 'rgba(0,0,0,0.035)',
    modalBg: '#FFFFFF',
  },
  dark: {
    bg: '#0F172A',
    card: '#1E293B',
    cardBorder: 'rgba(255,255,255,0.06)',
    unreadBg: '#1E2A47',
    primary: '#818CF8',
    primaryMuted: 'rgba(129,140,248,0.15)',
    success: '#34D399',
    danger: '#F87171',
    warning: '#FBBF24',
    text: '#F1F5F9',
    textSecondary: '#CBD5E1',
    textMuted: '#94A3B8',
    textFaint: '#64748B',
    divider: 'rgba(255,255,255,0.06)',
    inputBg: 'rgba(255,255,255,0.06)',
    bubbleIn: '#273449',
    bubbleInText: '#F1F5F9',
    bubbleOut: '#4F46E5',
    bubbleOutText: '#FFFFFF',
    noteBg: 'rgba(255,255,255,0.04)',
    modalBg: '#1E293B',
  },
};

export const callsStyles = StyleSheet.create({
  // ─── List ─────────────────────────────────────────────────────────
  searchWrap: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 8,
  },
  searchInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    height: 42,
    borderRadius: 12,
    paddingHorizontal: 12,
    borderWidth: 1,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    paddingVertical: 0,
  },
  convItem: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    paddingLeft: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderLeftWidth: 3,
    marginBottom: 8,
  },
  convRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  convName: {
    flex: 1,
    fontSize: 15,
  },
  unreadBadge: {
    minWidth: 20,
    height: 20,
    paddingHorizontal: 6,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  unreadBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#fff',
  },

  // ─── Conversation header ─────────────────────────────────────────
  convHeader: {
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    gap: 8,
  },
  headerBackBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
  },

  // ─── Timeline ─────────────────────────────────────────────────────
  dayDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginVertical: 14,
  },
  dayDividerLine: {
    flex: 1,
    height: 1,
  },
  dayDividerText: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  bubbleRow: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  bubble: {
    maxWidth: '85%',
    minWidth: 220,
    padding: 10,
    borderRadius: 14,
  },
  bubbleIn: {
    borderBottomLeftRadius: 4,
  },
  bubbleOut: {
    borderBottomRightRadius: 4,
  },
  smsBubble: {
    maxWidth: '82%',
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 16,
  },
  bubbleMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
    paddingHorizontal: 2,
    gap: 8,
  },
  metaText: {
    fontSize: 11,
  },
  metaLink: {
    fontSize: 11,
    fontWeight: '700',
  },
  playerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  playBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressTrack: {
    flex: 1,
    height: 4,
    borderRadius: 2,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 2,
  },
  summaryBox: {
    marginTop: 8,
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    gap: 6,
  },
  commentItem: {
    flexDirection: 'row',
    gap: 8,
    padding: 8,
    borderRadius: 10,
  },
  commentAvatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  commentInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 8,
  },
  commentInput: {
    flex: 1,
    minHeight: 38,
    maxHeight: 100,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 13,
  },
  commentSendBtn: {
    width: 38,
    height: 38,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noteRow: {
    flexDirection: 'row',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    marginBottom: 12,
  },
  loadOlderBtn: {
    alignSelf: 'center',
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 10,
    borderWidth: 1,
    marginBottom: 12,
  },
});
